### ISSUE TITLE
Support for Rails 4.2 ?

### ISSUE THREAD

**Issue by RandieM** [JDutil/contact_us#50]
With the introduction of Active Job and #deliver_later in Rails 4.2, I get the following warning:

DEPRECATION WARNING: `#deliver` is deprecated and will be removed in Rails 5. Use `#deliver_now` to deliver immediately or `#deliver_later` to deliver through Active Job.

So far, emails still get through, but may be this is something that needs to be updated in the gem.

Many thanks.

**Comment by JDutil** [comment]
Support for Rails 5 would be a more appropriate title as this is only warning that it will no longer work in Rails 5 so things are fine for now.  If you wouldn't mind submitting a PR updating the deprecation I'll merge to support Rails 5 otherwise this isn't a high priority for me at the moment.

**Comment by JDutil** [comment]
Released version 1.0.0 using deliver_now to fix deprecation.

**Comment by RandieM** [comment]
Well that was pretty fast! Thanks for updating. I was actually happy to give it a try myself, but, as I am not a programmer, it would have taken me much longer...
