### ISSUE TITLE
Feature: prepopulated subjects based on context

### ISSUE THREAD

**Issue by jdell64** [JDutil/contact_us#51]
Hey all!

If this is a feature you all like, I volunteer to try to implement it (I've never contributed to an open source project before, and would like the opportunity).

Basically, my use case for this is the user may click on this link in a few different areas. There is the general "Contact Us" button, where they could type in a subject, and a "Don't see what you are looking for, contact us, and we'll make it for you" type of context, where I would pre fill the subject line with "New Object Request" or something.

**Comment by JDutil** [comment]
I don't think that is something this project really needs.  It sounds pretty specific to your use case, and I'm not sure how you'd implement it in a generic way that doesn't complicate this gem that's intentionally kept light weight. I'd encourage you to just fork this project, and customize it to suit your own needs.  This was my first open source project, and it mainly served as a learning example which you can deconstruct however you'd like.
