### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by dninja777** [JDutil/contact_us#60]
when i deploy my app to heroku and try and test the contact form when i submit it does not work the route it takes me to is not there

**Comment by JDutil** [comment]
I would need more info to help troubleshoot this issue, such as, what's the url of your heroku app and what is the error or actual result displayed compared to your expectations? 

My assumption is that you probably haven't probably configured your heroku apps email add-on though. https://devcenter.heroku.com/articles/smtp

Going to close this out as I don't think it's an issue with the gem, but will re-open or help troubleshoot with more info around your problem and email add-on setup.
